permalink: /:year/:month/:day/:title.html
paginate: 50
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 张少杰
  email: zhangshao45612@163.com
  link: http://blog.csdn.net/zhangshao45612
  weibo: http://weibo.com/zhangshao45612
  github: https://github.com/zhangshao45612

# 站点信息
title: 张少杰的博客 
description: 张少杰的博客
url: http://zhangshao45612.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://pan.baidu.com/s/1dDfmpY5
favicon: http://pan.baidu.com/s/1dDfmpY5

# google analytics 设置
ga:
  id: UA-56952211-1
  url: zhangshao45612.github.io

# disqus 设置
disqus:
  shortname: zhangshao45612

# 主题设置，自动激活某个标签
active: 技术

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
